Fix/#148 fix cache provider negative ttl handling
doctrine/cache pull request #184
Opened 2016-10-26 10:48 UTC by Ocramius

Continuation of #148

This is a possible BC break for scenarios in which the consumer of the API explicitly used negative TTLs.

The current patch silently turns negative integers into `0` internally, but I'm not happy with it.

I changed the docblock documentation so that an unsigned integer is required. What do you folks think about throwing an exception instead of silently turning negatives into `0`? Too much of a breakage?

2016-10-26 10:54 UTC, alcaeus commented
> What do you folks think about throwing an exception instead of silently turning negatives into 0? Too much of a breakage?

TBH, I consider silently changing negative values to 0 more breakage than an exception - at least the latter will show up in the logs instead of just changing values.

2016-10-26 15:46 UTC, Ocramius commented
Agree, will implement that way then.

On 26 Oct 2016 12:54 p.m., "Andreas" <notifications@github.com> wrote:

> What do you folks think about throwing an exception instead of silently
> turning negatives into 0? Too much of a breakage?
>
> TBH, I consider silently changing negative values to 0 more breakage than
> an exception - at least the latter will show up in the logs instead of just
> changing values.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/cache/pull/184#issuecomment-256313954>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakFkst9yKKtg_e6vSiRImP9N36MUcks5q3zFdgaJpZM4KhBg1>
> .
>

2016-10-26 23:10 UTC, Ocramius commented
@malukenho can you take over here?

2017-08-25 06:32 UTC, lcobucci requested changes

2017-08-25 06:32 UTC, lcobucci commented on lib/Doctrine/Common/Cache/Exception/LifeTimeException.php
> +class LifeTimeException extends \RuntimeException
`final`

2017-08-25 06:32 UTC, lcobucci commented on lib/Doctrine/Common/Cache/Exception/LifeTimeException.php
> +    public static function fromNonIntegerLifetime($value)
` : self`

2017-08-25 06:32 UTC, lcobucci commented on lib/Doctrine/Common/Cache/Exception/LifeTimeException.php
> +    public static function fromNegativeLifetime()
` : self`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +    public function testSetNameSpace()
Namespace is a single word, therefore `testSetNamespace`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +    public function testSetNameSpace()
Also ` : void`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +        $this->assertSame('Foo', $cache->getNamespace());
`self::assert*`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +    public function testLifeTimeShouldBeAnIntegerValue($lifeTime)
` : void`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +    public function testSaveMultipleWithNegativeTtl()
` : void`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +        $data = array_map(function ($value) {
I think this is more readable:

```php
$data = array_column($this->provideDataToCache(), 0);
```

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +    public function providerNonIntegerLifeTime()
` : array`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/CacheTest.php
> +    public function testNoExpireWithNegativeTtl()
` : void`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/Exception/LifeTimeExceptionTest.php
> +class LifeTimeExceptionTest extends \PHPUnit_Framework_TestCase
`extends \Doctrine\Tests\DoctrineTestCase`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/Exception/LifeTimeExceptionTest.php
> +        $this->assertInstanceOf(LifeTimeException::class, $exception);
This is not needed by adding the return type declaration

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/Exception/LifeTimeExceptionTest.php
> +        $this->assertInstanceOf(LifeTimeException::class, $exception);
This is not needed by adding the return type declaration

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/Exception/LifeTimeExceptionTest.php
> +    public function testFromNonIntegerLifetime()
` : void`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/Exception/LifeTimeExceptionTest.php
> +    public function testFromNegativeLifetime()
` : void`

2017-08-25 06:32 UTC, lcobucci commented on tests/Doctrine/Tests/Common/Cache/Exception/LifeTimeExceptionTest.php
> +        $this->assertSame(
`self::assert*`

2019-11-11 10:24 UTC, Ocramius commented
Moved out of `1.9` milestone: not mergeable/workable at this point in time.

Anyone needing this, please feel free to pick it up.

2021-04-13 10:41 UTC, alcaeus commented
Closing since we are sunsetting this library. Please see #354 for more details. Thank you for your contribution!

2021-04-13 10:41 UTC, closed without merging