Do not force igbinary serializer for redis if the module is installed.
doctrine/cache pull request #211
Opened 2017-02-15 19:30 UTC by mvanbaak

This fixes https://github.com/doctrine/cache/issues/150

Also, the RedisCache is now inline with MemcachedCache in that it uses the serializer specified (or auto-set) on the passed Cache object.

2017-02-16 19:32 UTC, Ocramius requested changes

2017-02-16 19:32 UTC, Ocramius commented on tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
> -    public function testSerializerOptionWithOutIgbinaryExtension()
This is a BC break for those using igbinary

2017-02-16 21:28 UTC, mvanbaak commented on tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
> -    public function testSerializerOptionWithOutIgbinaryExtension()
yes, but unfortunately it's the only way to allow people to choose a serializer different from igbinary when the igbinary module is installed in their environment (which breaks a lot of things on PHP-7 and CommandLine scripts)
If you have a better way to do it I'm all ears. I already thought of adding an extra parameter but that will make things a lot more ugly, and will make the RedisCache even more different from the other implementations.

2017-02-16 21:34 UTC, Ocramius commented on tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
> -    public function testSerializerOptionWithOutIgbinaryExtension()
Then a new implementation is needed (different class name)

2017-02-16 21:40 UTC, mvanbaak commented on tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
> -    public function testSerializerOptionWithOutIgbinaryExtension()
Ok, I can do that :) Any ideas? I'm very bad at that. RedisWithPresetSerializerCache ?

2017-02-16 21:42 UTC, Ocramius commented on tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
> -    public function testSerializerOptionWithOutIgbinaryExtension()
Try something, then we review? :-P

In general, yes, a new symbol is a better solution than a BC break, especially on such a widespread library.

2017-03-23 10:43 UTC, apflieger commented
Any news? I can't wait to have that :)

2017-03-23 21:24 UTC, lcobucci commented
@apflieger as per @Ocramius the approach to solve this issue would be having a new symbol instead of breaking BC.
The author of the PR - probably - didn't have time to address this however you're quite welcome to send us another PR so that we can review it 😉

2017-03-25 12:38 UTC, mvanbaak commented
Sorry all, it took some time.

Didn't have time to do this earlier (and we were using my fork in production so the urgent need was no longer there)

2017-04-12 07:32 UTC, ishuowang commented
In my project with RedisCache, because forced igbinary serializer caused some problems, then I replaced with PredisCache. I think in the creation of the client can provide an optional parameter to determine the OPT_SERIALIZER way.
Some code:
public function setRedis(Redis $redis, $opt_serializer = false)
    {
        $opt_serializer = $opt_serializer?:$this->getSerializerValue();
        $redis->setOption(Redis::OPT_SERIALIZER, $opt_serializer );
        $this->redis = $redis;
    }

2017-05-01 06:13 UTC, lcobucci commented
@mvanbaak no worries, we're all pretty busy 😄 

Can you check these failing tests?

2017-12-06 11:32 UTC, yellow1912 commented
Any news on this? Seem like the class name is already changed as advised by @Ocramius

2017-12-07 19:32 UTC, alcaeus commented
> Any news on this?

No, still waiting on test fixes from @mvanbaak as asked by @lcobucci.

2021-04-13 10:42 UTC, alcaeus commented
Closing since we are sunsetting this library. Please see #354 for more details. Thank you for your contribution!

2021-04-13 10:42 UTC, closed without merging